version: '3.9'

services:
    backend:
        image: extender777/boiler
        ports:
            - '8045:3000'
        environment:
            - NODE_ENV=production
            - OPENAI_KEY=${OPENAI_KEY}
            - DEEPSEEK_KEY=${DEEPSEEK_KEY}
            - GOOGLE_KEY=${GOOGLE_KEY}
            - CLAUDE_KEY=${CLAUDE_KEY}
            - GROK_KEY=${GROK_KEY}
            - UNSPLASH_API_KEY=${UNSPLASH_API_KEY}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GA_API_SECRET=${GA_API_SECRET}
            - MONGODB_URI=mongodb://mongodb:27017/boiler
            - STRIPE_KEY=${STRIPE_KEY}
            - STRIPE_WH_SECRET=${STRIPE_WH_SECRET}
            - JWT_SECRET=${JWT_SECRET}
            - EMAIL=${EMAIL}
            - FROM_EMAIL=${FROM_EMAIL}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - FRONTEND_URL=https://Boiler.pro
        depends_on:
            - mongodb
        restart: unless-stopped
        volumes:
            - ./google.json:/app/google.json

    mongodb:
        image: mongo:latest
        volumes:
            - mongodb_data:/data/db
        restart: unless-stopped
        logging:
            driver: none

volumes:
    mongodb_data:
